FROM devkitpro/devkitppc:latest AS builder

WORKDIR /app
COPY . .

# Ustawienie zmiennych środowiskowych pod GameCube
ENV GEKKO=1
ENV HW_DOL=1

# Kompilacja projektu pod profil GameCube
RUN make -f Makefile.gamecube || make PLATFORM=gamecube

FROM scratch AS exporter
# Kopiowanie wygenerowanego pliku .dol do artefaktów GitHuba
COPY --from=builder /app/*.dol /