FROM devkitpro/devkitppc:latest AS builder

WORKDIR /app
COPY . .

# Uruchomienie kompilacji z użyciem Makefile.gamecube
RUN make -f Makefile.gamecube

FROM scratch AS exporter
# Kopiowanie wygenerowanego pliku .dol do wyjścia
COPY --from=builder /app/*.dol /