name: Kompilacja Scratch Everywhere - GameCube

on: [workflow_dispatch]

jobs:
  build-gamecube:
    name: Budowanie wersji GameCube
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu z repozytorium
        uses: actions/checkout@v4

      - name: Kompilacja GameCube przez Docker
        run: |
          mkdir -p output_gamecube
          docker build -f docker/Dockerfile.gamecube --target exporter -o ./output_gamecube .

      - name: Zapisanie gotowego pliku GameCube (.dol)
        uses: actions/upload-artifact@v4
        with:
          name: Gra-GameCube-Aplikacja
          path: ./output_gamecube